### ISSUE TITLE
GeoPointToPgeoPoint is used for pointer type

### ISSUE THREAD

**Issue by troian** [web-ridge/utils-go#3]
In `convert_input.go` boilergql.GeoPointToPgeoPoint used with pointer receiver.

**expected:**
`boilergql.PointerGeoPointToPgeoPoint` should be used instead

**Comment by RichardLindhout** [comment]
Strange, are you sure it's a pointer in your generated_models.go from gqlgen?
Based on this function it should https://github.com/web-ridge/gqlgen-sqlboiler/blob/master/convert.go#L879 when there is a * in front of type.

**Comment by troian** [comment]
Yah, `boilergql.PointerGeoPointToPgeoPoint` was set manualy
<img width="1118" alt="Screen Shot 2020-05-11 at 8 24 19 AM" src="https://user-images.githubusercontent.com/2477474/81561236-e1a43500-9360-11ea-911d-2a9bf4cde40f.png">

**Comment by RichardLindhout** [comment]
I know where this is coming from, it is caused by custom types which are imported from other packages where the * is stripped from the type in gqlgen-sqlboiler. 

I have a fix already but testing it internally!

**Comment by RichardLindhout** [comment]
This should be fixed in gqlgen-sqlboiler@v2.0.10

**Comment by troian** [comment]
Cheers, I'll check

**Comment by RichardLindhout** [comment]
Does it work?

**Comment by troian** [comment]
Yah, sorry for late response

**Comment by RichardLindhout** [comment]
Haha no worries, soon enough just curious :)
