### ISSUE TITLE
Time conversions are tied to timezone

### ISSUE THREAD

**Issue by troian** [web-ridge/utils-go#5]
`IntToTimeTime` for example returns local time. Does it make sense to turn into?
```go
func IntToTimeTime(v int) time.Time {
	return time.Unix(int64(v), 0).UTC()
}
```

**Comment by RichardLindhout** [comment]
I think we should output is as it is stored, so no UTC after getting it from database

**Comment by RichardLindhout** [comment]
The int should be UNIX and unix should be already UTC since it's the definition of unix but it's always hard to work with timezones etc so not 100% sure about this.

**Comment by RichardLindhout** [comment]
When storing it already converts to UTC: https://golang.org/pkg/time/#Time.Unix

**Comment by RichardLindhout** [comment]
So I think you're code from pull request was fine 👍

**Comment by RichardLindhout** [comment]
I think it's a hard problem maybe. In your API it would depend in some api's you wan't to return the local time and in some you don't want that.

**Comment by troian** [comment]
Thats quite strange though. We send UTC timestamp but IntToTimeTime converts it to local

**Comment by RichardLindhout** [comment]
Ok hmm strange maybe set the TZ= environment variable. I always have difficulties with timezone with understanding them.

**Comment by RichardLindhout** [comment]
I think setting TZ= is maybe a good idea.

**Comment by RichardLindhout** [comment]
If you use it in docker containers be aware that some containers don't include all timestamps. It did cost us quite some time to find that out back then :-D
![download](https://user-images.githubusercontent.com/6492229/82364071-11ada100-9a0f-11ea-9245-2d60c3c468d3.jpeg)

**Comment by RichardLindhout** [comment]
If you use alphine I think it was something like this.
```
FROM alpine:3.11

ARG TZ='Europe/Amsterdam'

ENV DEFAULT_TZ ${TZ}

RUN apk upgrade --update \
  && apk add -U tzdata \
  && cp /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime \
  && apk del tzdata \
  && rm -rf \
  /var/cache/apk/*

CMD ["ls"]

```
